### PR TITLE
Adapted description to use of TestCaseTrait

### PR DESCRIPTION
**Pull request by arneschuldt**
Before, the description still referred to the other TestCase previously used

### CODE REVIEW

**Comment by lex111** [comment]
@arneschuldt Could you change the branch to an earlier one?

**Comment by arneschuldt** [comment]
@lex111 Done so.

**Comment by lex111** [comment]
You need to update the `master` branch (arneschuldt:master) locally to `7.0`. Something like this:

```
git merge origin 7.0
```

**Comment by arneschuldt** [comment]
@lex111 Sorry, I did not have have a local version (made my few changes directly in the GitHub editor).

I now have a local version but I am not sure what to do.

**Comment by lex111** [comment]
Then make your changes from branch `7.0` in GitHub, not from `master` and create a new PR.

**Comment by sebastianbergmann** [comment]
Please send a new pull request. Thanks.

**Pull request closed without merging**
