### PR TITLE
Adding reference link to installation of DbUnit

### PR DESCRIPTION
**Pull request by jmauerhan**
It took me a few tries to find out how to install the extension, I thought it would be helpful to add a link to those instructions in this section.

### CODE REVIEW

**Comment by lex111** [comment]
Hey @jmauerhan 

Please make this pull request against the oldest branch (7.0 may be) where it applies.

**Comment by jmauerhan** [comment]
I believe I'll have to open a new PR, because mine was originally based off master. Thanks for letting me know, I'll do one based on 7.0.

**Comment by lex111** [comment]
No, you don't have to do this! You can change the branch in the existing PR.

**Comment by lex111** [comment]
Just click on Edit and you can change the branch.

image

**Comment by jmauerhan** [comment]
Hi @lex111 - when I originally tried to do that, it looked like it was pulling in a bunch of other changes, but when I tried again I guess it worked :)

**Comment by lex111** [comment]
> This branch cannot be rebased due to conflicts

Strange, perhaps for simplicity, since you have already opened #101, will you close this PR again? :)

**Pull request closed without merging**
