### PR TITLE
Fix: Add cacheResult to default phpunit.xml

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds `cacheResult` to default `phpunit.xml`

Related to https://github.com/sebastianbergmann/phpunit/pull/3092.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
This needs to go into the `7.3` branch.

**Comment by localheinz** [comment]
@sebastianbergmann 

Updated!

**Comment by keradus** [comment]
Milestone for https://github.com/sebastianbergmann/phpunit/pull/3092 was 7.2, why 7.3 for docs ?

**Comment by sebastianbergmann** [comment]
@keradus is right :) Sorry, this needs to go into `7.2`.

**Comment by sebastianbergmann** [comment]
I was wrong that @keradus is right :-)

See https://github.com/sebastianbergmann/phpunit/blob/7.3/ChangeLog-7.3.md#730---2018-08-03

`cacheResult` was added in PHPUnit 7.3.

**Comment by keradus** [comment]
feature added in 7.2, config for it in 7.3, got it :+1:

**Comment by localheinz** [comment]
Thank you, @keradus and @sebastianbergmann!

**Pull request merged**
