### PR TITLE
Fix some errors on examples and some tips

### PR DESCRIPTION
**Pull request by Rodrigo-Barros**
Hi I did see some errors on docs and I want help update these, and also I add some tips to new users like me.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Please make this against the oldest branch possible. Thanks!

**Comment by Rodrigo-Barros** [comment]
Hi, 
I was looking the tags and I did see the 7.0 as a oldest branch its right?
cause the part that I change do not cover the new features in newer versions.
I don't know which is the oldest  branch, can you give some clue?

**Comment by sebastianbergmann** [comment]
The oldest branch is `7.0`. The change should be made against the oldest branch where it is relevant/required.

**Comment by Rodrigo-Barros** [comment]
Hi Thanks for the help, now I made another pull request in 7.0 branch as you said, I hope be right.
here the reference: https://github.com/sebastianbergmann/phpunit-documentation-english/pull/195

**Pull request closed without merging**
