### PR TITLE
Fix: Adjust wording

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] adjusts the wording

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Are you still planning to work on this?

**Comment by localheinz** [comment]
@sebastianbergmann 

Would it be ok for you to slice the work into smaller chunks?

**Comment by sebastianbergmann** [comment]
That would make both our lives easier, wouldn't it? :-)

**Comment by localheinz** [comment]
@sebastianbergmann 

Looks like the changes I applied here are not necessary anymore.

**Pull request closed without merging**
